spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/chatrop}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:pass}

spring.jpa.hibernate.ddl-auto=update

# Para ver las consultas SQL en la consola y aprender qué hace Spring:
spring.jpa.show-sql=true

# Configuración de CORS dinámica
app.cors.allowed-origins=http://localhost:8080
